# Generated by Django 3.2.3 on 2021-05-21 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=160)),
                ('use', models.TextField(max_length=256)),
                ('effects', models.TextField(max_length=256)),
                ('side_effects', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('мужчина', 'Мужчина'), ('женщина', 'Женщина')], max_length=10)),
                ('birth_date', models.DateField()),
                ('address', models.TextField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.TextField(max_length=256)),
                ('symptoms', models.TextField(max_length=256)),
                ('diagnosis', models.TextField(max_length=256)),
                ('doctor', models.TextField(max_length=256)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.patient')),
            ],
        ),
    ]
